---
- name: Set script into .bashrc
  ansible.builtin.blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    append_newline: true
    prepend_newline: true
    block: |
      if [[ -n $VSCODE_SH_INIT_COMMAND ]]; then
        echo "Running: $VSCODE_SH_INIT_COMMAND"
        eval "$VSCODE_SH_INIT_COMMAND"
      fi

      alias hello_command="echo Hello World!"
    insertafter: EOF
