---
- name: Copy preferences config to /tmp
  ansible.builtin.template:
    src: "{{ config_source ~ '/' ~ (item.value | basename) }}"
    dest: "{{ item.value }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "644"
  loop: "{{ prefs_tmp_files | dict2items }}"

- name: Parse variable
  ansible.builtin.set_fact:
    user_config_dir: "{{ user_config_dir }}"

- name: Ensure the user config directory exists
  ansible.builtin.file:
    path: "{{ item.value }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "755"
    state: directory
  loop: "{{ user_config_dir | dict2items }}"

- name: Copy background image
  ansible.builtin.copy:
    src: "{{ private_config_source ~ '/' ~ desktop_background_image }}"
    dest: "{{ user_config_dir.backgrounds }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "644"

- name: Add git-core/ppa
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Do apt upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Install packages from repository
  ansible.builtin.include_tasks:
    file: install_packages.yml

- name: Install application from URL
  ansible.builtin.include_tasks:
    file: install_application.yml
  loop: "{{ application_from_url }}"
  loop_control:
    label: "{{ item.name }}"

- name: Customize user bashrc
  ansible.builtin.include_tasks:
    file: customize_bashrc.yml
