---
config_source: "{{ root_dir }}/files/config"
private_config_source: "{{ root_dir }}/files/private/config"

prefs_tmp_files:
  background_prefs: /tmp/background.prefs
  interface_prefs: /tmp/interface.prefs
  screensaver_prefs: /tmp/screensaver.prefs
  gnome_shell_prefs: /tmp/gnome_shell.prefs
  gnome_terminal_prefs: /tmp/gnome_terminal.prefs
  gtk_prefs: /tmp/gtk.prefs

user_config_dir:
  backgrounds: "/home/{{ ansible_user }}/.local/share/backgrounds"
  bin: "/home/{{ ansible_user }}/.local/bin"

desktop_background_image: autosetup-desktop-background.jpg

application_from_url:
  - name: yq
    version: 4.44.6
    url: https://github.com/mikefarah/yq/releases/download/v#application_version#/yq_linux_amd64
    binary_files:
      - name: yq
        file: yq_linux_amd64

  - name: go
    version: 1.23.4
    url: https://go.dev/dl/go#application_version#.linux-amd64.tar.gz
    binary_files:
      - name: go
        file: bin/go

      - name: gofmt
        file: bin/gofmt
    is_archive: true

  - name: graalvm-jdk
    version: 23.0.2
    url: >
      https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-#application_version#/graalvm-community-jdk-#application_version#_linux-x64_bin.tar.gz
    binary_files:
      - name: java
        file: bin/java

      - name: javac
        file: bin/javac

      - name: javap
        file: bin/javap

      - name: jar
        file: bin/jar

      - name: keytool
        file: bin/keytool

      - name: native-image
        file: bin/native-image

      - name: native-image-configure
        file: bin/native-image-configure
    is_archive: true

  - name: php
    version: 8.4.2
    url: https://www.php.net/distributions/php-#application_version#.tar.gz
    binary_files:
      - name: php
        file: bin/php
    packages_dependencies:
      - libxml2-dev
      - libssl-dev
      - libsqlite3-dev
      - libcurl4-openssl-dev
      - libpng-dev
      - libonig-dev
      - libxslt1-dev
      - libzip-dev
    is_archive: true
    is_compiled: true
    compile_commands:
      - >
        ./configure --prefix=/opt/php --enable-intl --enable-exif --enable-sockets --enable-mbstring --enable-gd
        --with-curl --with-openssl --with-xsl --with-zip --with-zlib
      - make -j8
      - make install

  - name: composer
    version: 2.8.4
    url: https://getcomposer.org/download/#application_version#/composer.phar
    binary_files:
      - name: composer
        file: composer.phar
